export const ERROR_CODES = {
  // Common
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  CONFLICT: 'CONFLICT',
  OPTIMISTIC_LOCK_FAILED: 'OPTIMISTIC_LOCK_FAILED',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_EMAIL_UNVERIFIED: 'AUTH_EMAIL_UNVERIFIED',
  AUTH_MFA_REQUIRED: 'AUTH_MFA_REQUIRED',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_REFRESH_REUSED: 'AUTH_REFRESH_REUSED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',

  // Patient / authorization
  PATIENT_SCOPE_DENIED: 'PATIENT_SCOPE_DENIED',
  CLINIC_SCOPE_DENIED: 'CLINIC_SCOPE_DENIED',
  RELATIONSHIP_REQUIRED: 'RELATIONSHIP_REQUIRED',
  BREAK_GLASS_REASON_REQUIRED: 'BREAK_GLASS_REASON_REQUIRED',

  // Encounter state machine (docs/api.md section 23)
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  ENCOUNTER_CLOSE_REQUIRES_SIGNED_RECORD: 'ENCOUNTER_CLOSE_REQUIRES_SIGNED_RECORD',

  // Appointment / QR / Queue (docs/api.md sections 21-22)
  APPOINTMENT_SLOT_UNAVAILABLE: 'APPOINTMENT_SLOT_UNAVAILABLE',
  APPOINTMENT_PATIENT_TIME_CONFLICT: 'APPOINTMENT_PATIENT_TIME_CONFLICT',
  APPOINTMENT_NOT_CANCELLABLE: 'APPOINTMENT_NOT_CANCELLABLE',
  QR_INVALID: 'QR_INVALID',
  QR_EXPIRED: 'QR_EXPIRED',
  QR_REVOKED: 'QR_REVOKED',
  KIOSK_DEVICE_UNAUTHORIZED: 'KIOSK_DEVICE_UNAUTHORIZED',
  QUEUE_TICKET_NOT_WAITING: 'QUEUE_TICKET_NOT_WAITING',
  QUEUE_EMPTY: 'QUEUE_EMPTY',

  // Clinical / EMR (docs/api.md sections 24-29)
  DIAGNOSIS_RATIONALE_REQUIRED: 'DIAGNOSIS_RATIONALE_REQUIRED',
  CLINICAL_ORDER_INVALID_TRANSITION: 'CLINICAL_ORDER_INVALID_TRANSITION',
  MEDICAL_RECORD_ALREADY_SIGNED: 'MEDICAL_RECORD_ALREADY_SIGNED',
  MEDICAL_RECORD_COMPLETION_REQUIRED: 'MEDICAL_RECORD_COMPLETION_REQUIRED',
  MEDICAL_RECORD_REOPEN_REASON_REQUIRED: 'MEDICAL_RECORD_REOPEN_REASON_REQUIRED',
  CLINICAL_PLAN_REQUIRED_FOR_ACTIVATION: 'CLINICAL_PLAN_REQUIRED_FOR_ACTIVATION',

  // Workflow / BPM (docs/api.md sections 27-28)
  WORKFLOW_CYCLE_DETECTED: 'WORKFLOW_CYCLE_DETECTED',
  WORKFLOW_TASK_ALREADY_CLAIMED: 'WORKFLOW_TASK_ALREADY_CLAIMED',
  WORKFLOW_STEP_MANDATORY_CANNOT_MODIFY: 'WORKFLOW_STEP_MANDATORY_CANNOT_MODIFY',
  WORKFLOW_INSTANCE_INCOMPLETE_MANDATORY_TASKS: 'WORKFLOW_INSTANCE_INCOMPLETE_MANDATORY_TASKS',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
