export const ERROR_CODES = {
  // Common
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  CONFLICT: 'CONFLICT',
  OPTIMISTIC_LOCK_FAILED: 'OPTIMISTIC_LOCK_FAILED',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_EMAIL_UNVERIFIED: 'AUTH_EMAIL_UNVERIFIED',
  AUTH_MFA_REQUIRED: 'AUTH_MFA_REQUIRED',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_REFRESH_REUSED: 'AUTH_REFRESH_REUSED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',

  // Patient / authorization
  PATIENT_SCOPE_DENIED: 'PATIENT_SCOPE_DENIED',
  CLINIC_SCOPE_DENIED: 'CLINIC_SCOPE_DENIED',
  RELATIONSHIP_REQUIRED: 'RELATIONSHIP_REQUIRED',
  BREAK_GLASS_REASON_REQUIRED: 'BREAK_GLASS_REASON_REQUIRED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
