import { Injectable } from '@nestjs/common';
import { randomUUID } from 'crypto';
import { PrismaService } from '../../core/database/prisma.service';
import { IssuedRefreshToken } from './token.service';

export interface DeviceContext {
  deviceLabel?: string;
  ip?: string;
  userAgent?: string;
}

@Injectable()
export class RefreshSessionsRepository {
  constructor(private readonly prisma: PrismaService) {}

  createFamily(userId: string, issued: IssuedRefreshToken, context: DeviceContext) {
    return this.prisma.refreshSession.create({
      data: {
        userId,
        familyId: randomUUID(),
        tokenHash: issued.tokenHash,
        expiresAt: issued.expiresAt,
        deviceLabel: context.deviceLabel,
        ip: context.ip,
        userAgent: context.userAgent,
      },
    });
  }

  /** `id` is pre-generated by the caller (AuthService.refresh) so it can be
   * committed into the old session's `replacedById` via the atomic
   * `markRotated` CAS *before* this row is created — see markRotated's
   * comment for why ordering matters here. */
  createInFamily(
    id: string,
    userId: string,
    familyId: string,
    issued: IssuedRefreshToken,
    context: DeviceContext,
  ) {
    return this.prisma.refreshSession.create({
      data: {
        id,
        userId,
        familyId,
        tokenHash: issued.tokenHash,
        expiresAt: issued.expiresAt,
        deviceLabel: context.deviceLabel,
        ip: context.ip,
        userAgent: context.userAgent,
      },
    });
  }

  findByTokenHash(tokenHash: string) {
    return this.prisma.refreshSession.findUnique({ where: { tokenHash } });
  }

  /**
   * SECURITY FIX: compare-and-swap (`revokedAt: null` in the where clause) so
   * two concurrent `refresh()` calls presenting the same still-valid token
   * cannot both win. Previously this was a plain `update`, called only after
   * a separate, unlocked `findByTokenHash` read — two racing requests would
   * both pass that read (neither had committed yet) and both would rotate,
   * silently forking two child sessions from one token with reuse-detection
   * never triggering. Returns the row count so the caller can detect the
   * loser and treat it as reuse instead of pretending to succeed.
   */
  markRotated(id: string, replacedById: string) {
    return this.prisma.refreshSession.updateMany({
      where: { id, revokedAt: null },
      data: { revokedAt: new Date(), revokedReason: 'rotated', replacedById },
    });
  }

  revoke(id: string, reason: string) {
    return this.prisma.refreshSession.update({
      where: { id },
      data: { revokedAt: new Date(), revokedReason: reason },
    });
  }

  revokeFamily(familyId: string, reason: string) {
    return this.prisma.refreshSession.updateMany({
      where: { familyId, revokedAt: null },
      data: { revokedAt: new Date(), revokedReason: reason },
    });
  }
}
