import { INestApplication } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { DocumentBuilder, OpenAPIObject, SwaggerModule } from '@nestjs/swagger';
import { NextFunction, Request, Response, static as expressStatic } from 'express';
import { dirname } from 'path';
import { AppConfiguration } from '../config/configuration';

export const DOCUMENTATION_CACHE_CONTROL =
  'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';

export interface OpenApiEndpoints {
  version: string;
  legacyUiPath: string;
  versionedUiPath: string;
  versionedJsonPath: string;
}

interface HeaderWriter {
  setHeader(name: string, value: string): unknown;
}

function documentationVersion(app: INestApplication): string {
  const config = app.get(ConfigService<AppConfiguration, true>);
  return config.get('documentation', { infer: true }).version;
}

function setDocumentationNoCacheHeaders(res: HeaderWriter): void {
  res.setHeader('Cache-Control', DOCUMENTATION_CACHE_CONTROL);
  res.setHeader('Pragma', 'no-cache');
  res.setHeader('Expires', '0');
}

function noCacheDocumentation(_req: Request, res: Response, next: NextFunction): void {
  setDocumentationNoCacheHeaders(res);
  next();
}

function registerDocumentationNoCacheHeaders(app: INestApplication): void {
  // /api/docs covers the legacy UI and every release-versioned UI asset.
  // The two sibling paths are the legacy JSON/YAML endpoints generated by
  // @nestjs/swagger and therefore need explicit middleware mounts.
  app.use('/api/docs', noCacheDocumentation);
  app.use('/api/docs-json', noCacheDocumentation);
  app.use('/api/docs-yaml', noCacheDocumentation);
}

function registerDocumentationStaticAssets(app: INestApplication, versionedUiPath: string): void {
  const assetsPath = dirname(require.resolve('swagger-ui-dist/package.json'));
  const assets = expressStatic(assetsPath, {
    index: false,
    redirect: false,
    setHeaders: setDocumentationNoCacheHeaders,
  });

  // @nestjs/swagger's built-in express.static layer overwrites Cache-Control.
  // Serving the same pinned assets first lets us enforce no-cache headers while
  // its generated HTML and swagger-ui-init.js handlers continue to work.
  app.use(versionedUiPath, assets);
}

function registerLegacyUiRedirect(
  app: INestApplication,
  legacyUiPath: string,
  versionedUiPath: string,
): void {
  const adapter = app.getHttpAdapter();
  const redirect = (_req: Request, res: Response) => adapter.redirect(res, 302, versionedUiPath);

  // A temporary, no-store redirect preserves the familiar entry point without
  // loading the four-hour-cached legacy swagger-ui-init.js asset. It must not be
  // permanent because the destination changes on every documentation release.
  adapter.get(legacyUiPath, redirect);
  adapter.get(`${legacyUiPath}/`, redirect);
}

export function createOpenApiDocument(app: INestApplication): OpenAPIObject {
  const version = documentationVersion(app);
  const swaggerConfig = new DocumentBuilder()
    .setTitle('DermaHealth Backend API')
    .setDescription('Clinic workflow backend: identity, scheduling, clinical, workflow, EMR, CRM.')
    .setVersion(version)
    .addBearerAuth()
    .addCookieAuth('refresh_token')
    .build();

  return SwaggerModule.createDocument(app, swaggerConfig);
}

export function configureOpenApi(app: INestApplication): OpenApiEndpoints {
  const version = documentationVersion(app);
  const legacyUiPath = '/api/docs';
  const versionedUiPath = `${legacyUiPath}/${version}`;
  const versionedJsonPath = `${versionedUiPath}/openapi.json`;
  const versionedYamlPath = `${versionedUiPath}/openapi.yaml`;
  const document = createOpenApiDocument(app);

  registerDocumentationNoCacheHeaders(app);
  registerDocumentationStaticAssets(app, versionedUiPath);

  // Register the release-specific route first so its handlers take precedence
  // over the legacy UI's broad static-assets middleware.
  SwaggerModule.setup(versionedUiPath, app, document, {
    jsonDocumentUrl: versionedJsonPath,
    yamlDocumentUrl: versionedYamlPath,
    swaggerUrl: versionedJsonPath,
    customSiteTitle: `DermaHealth API ${version}`,
  });

  // Keep @nestjs/swagger's established /api/docs-json and /api/docs-yaml
  // endpoints for machine clients, without re-registering cache-prone legacy
  // UI assets. Human users entering /api/docs are redirected below.
  SwaggerModule.setup(legacyUiPath, app, document, {
    swaggerUiEnabled: false,
  });
  registerLegacyUiRedirect(app, legacyUiPath, versionedUiPath);

  return { version, legacyUiPath, versionedUiPath, versionedJsonPath };
}
